baseurl = "https://www.alliafi.com"
title = "Alli á mjólkurbílnum"
theme = "hugo-coder"
languagecode = "is"
defaultcontentlanguage = "is"

paginate = 100
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "alliamjolkurbilnum"

[params]
    author = "Aðalsteinn Ólafsson"
    info = "Melgerði, Eyjarfirði. 1917 - 1998"
    description = "Þessi síða heldur utan um ljóð eftir hann afa minn, Aðalstein Ólafsson"
    keywords = "blog,developer,personal"
    avatarurl = "images/Alli.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Viðhaldið af Birgi Hrafni Sigurðssyni"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
# [[params.social]]
#     name = "Github"
#     icon = "fab fa-github fa-2x"
#     weight = 1
#     url = "https://github.com/johndoe/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter fa-2x"
#     weight = 3
#     url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
    name = "Ljóð"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Um Alla"
    weight = 2
    url = "/about/"
